name: Check realme Thread Content

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allow manual trigger

jobs:
  check-thread:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download last content artifact (if exists)
      uses: actions/download-artifact@v4
      with:
        name: last-content
        path: .

    - name: Run thread checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python check_thread.py

    - name: Upload new last content
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: last-content
        path: last_content.json
